services:
  consul:
    container_name: laomaDJConsul
    image: consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
  jaeger:
    container_name: laomaDJJaeger
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true
  redis:
    container_name: laomaDJRedis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  mysql:
    container_name : laomaDJMySQL
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    #  MYSQL_DATABASE: laomadj_customer
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
